### ISSUE TITLE
Documentation error in "Create a simulated drone"

### ISSUE THREAD

**Issue by cartovarc** [Parrot-Developers/olympe#1]
In [user guide documentation](https://developer.parrot.com/docs/olympe/userguide.html), when I try yo access to "sphinx" links, it redirect me to [this](http://woody.parrot.biz:8080/view/sphinx-doc/job/sphinx-release-doc/PARAM_PACKAGE_VERSION=release,PARAM_SPHINX_DOC_VERSION=internal,label=slave-ubuntu-xenial/HTML_Report/)
_____________________________________
![Screenshot from 2019-05-09 13-16-12](https://user-images.githubusercontent.com/26529546/57476708-cb026400-725c-11e9-8a16-bc9d42ec0ec3.png)
_____________________________________
I have this ubuntu version:
![Screenshot from 2019-05-09 13-16-32](https://user-images.githubusercontent.com/26529546/57476709-cb026400-725c-11e9-9dc9-f8b4c051929e.png)
_____________________________________
I am using Google Chrome browser
![Screenshot from 2019-05-09 13-16-48](https://user-images.githubusercontent.com/26529546/57476710-cb026400-725c-11e9-9f14-6c2562267a79.png)
_____________________________________
Same happens with Firefox browser
![Screenshot from 2019-05-09 13-23-16](https://user-images.githubusercontent.com/26529546/57477146-a78be900-725d-11e9-8e71-1e589dd7b17e.png)

**Comment by ndessart** [comment]
Thanks for reporting this. It was just a dead link, sorry.
Parrot-Sphinx documentation is available at: https://developer.parrot.com/docs/sphinx/
