### ISSUE TITLE
Unable to change stream resolution

### ISSUE THREAD

**Issue by arumugam666** [Parrot-Developers/olympe#11]
Changing recording resolution does not change stream resolution.
I use this to set resolution to 4k video
        self.drone(set_recording_mode(0,0,0,0,0)).wait()
But this has no effect on the quality of the stream.

**Comment by ndessart** [comment]
On Anafi there is no way to control the video **streaming** resolution directly. The [set_recording_mode](https://developer.parrot.com/docs/olympe/arsdkng_camera.html#olympe.messages.camera.set_recording_mode) message changes the video **recording** mode. This could only have an incidental effect on the video **streaming** resolution.
 
For the Anafi, the video stream resolution is tied to the current [camera mode](https://developer.parrot.com/docs/olympe/arsdkng_camera.html#olympe.messages.camera.set_camera_mode) (photo capture or video recording).
In the video recording mode, the **streaming** resolution is 1280x720. In the photo mode, the video **streaming** resolution is 1024x768.

As far as I can tell, there is no issue with Olympe here. If you need any help with Olympe, please use the [developer forum](https://forum.developer.parrot.com/c/anafi/olympe) instead, Thanks

**Comment by arumugam666** [comment]
Thank you!
