### ISSUE TITLE
error in install olympe-linux dependencies

### ISSUE THREAD

**Issue by cartovarc** [Parrot-Developers/olympe#13]
Hi!
When I try automatic install with ./products/olympe/linux/env/postinst give me this error:

Anyone get this error? native-wrapper.sh apparently does not exist.
```
/home/parrot-dev/code/parrot-groundsdk/products/olympe/linux/env/setenv: línea 51: /home/parrot-dev/code/parrot-groundsdk/out/olympe-linux/final/native-wrapper.sh: No existe el archivo o el directorio
/home/parrot-dev/code/parrot-groundsdk/products/olympe/linux/env/setenv: /home/parrot-dev/code/parrot-groundsdk/.python//py3/bin/pip: /home/parrot-dev/code/parrot-groundsdk/.python/py3/bin/python: intérprete erróneo: No existe el archivo o el directorio
```

I am using Ubuntu 18.04

**Comment by ndessart** [comment]
Hi @cartovarc 

This issue has been fixed in Olympe 1.2.0.
You should update to Olympe 1.2.0 (`repo sync`) and rebuild it following the installation procedure from there.

Thanks
