### ISSUE TITLE
Error logged every time an event listener is called

### ISSUE THREAD

**Issue by kristiandreher** [Parrot-Developers/olympe#18]
Every time an event listener (https://developer.parrot.com/docs/olympe/olympeapi.html#olympe.EventListener) is called the the following error is shown in the logs:

`06:30:57.663 ardrone3.PilotingState.NavigateHomeStateChanged(state=NavigateHomeStateChanged_State.unavailable, reason=NavigateHomeStateChanged_Reason.disabled)
exception calling callback for <Future at 0x7ff09c79a240 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/home/kristian/code/flycam/groundsdk/packages/olympe/src/olympe/arsdkng/expectations.py", line 224, in <lambda>
    self._running_subscribers.pop(id(subscriber)),
KeyError: 140671439079632
`

I would suspect that this is due to the spelling error on this line (subsriber -> subscriber):
https://github.com/Parrot-Developers/olympe/blob/master/src/olympe/arsdkng/expectations.py#L223

I am using Olympe 1.2.0

**Comment by ndessart** [comment]
Thanks for reporting this issue.
This should be fixed in the upcoming 1.2.1 release.

**Comment by ndessart** [comment]
This has been fixed in Olympe 1.2.1
