### ISSUE TITLE
ip and wifi setup for multiple anafi connecting to the same host pc

### ISSUE THREAD

**Issue by snakehaihai** [Parrot-Developers/olympe#21]
Hi
I`m planning to use anafi for my research project to use anafi to create sth like this https://github.com/tau-adl/Tello_ROS_ORBSLAM . 
May I ask how do i config the anafi to connect to the same host pc? Do I set the static IP for them or what should I do?
Where do i get the camera feed concurrently? 
Is there any place that I can look for any tutorial?

Regards
Dr Yuan Shenghai

**Comment by JeromeBouvard** [comment]
Not possible.
