### ISSUE TITLE
Issue with repo init

### ISSUE THREAD

**Issue by Interaze** [Parrot-Developers/olympe#25]
When I attempt to follow the installation instructions, the repo init fails. This is provisioned with:
```
file=sys.stderr)
        ^
SyntaxError: invalid syntax
```
I updated the alias of python to be python3 (Ubuntu 18.04), but it doesn't appear to have made a change. Any insight would be appreciated.

**Comment by wjwwdb** [comment]
You can try to open hooks.py and delete ", file=sys.stderr" in the three lines of code in the figure below. This is what I did and the test has been successful.
![111](https://user-images.githubusercontent.com/38752065/103746183-a404c280-503b-11eb-9c75-6aa04272cdfb.png)

**Comment by markpdxt** [comment]
On Ubuntu 18.04, just setting the python alias was successful for me.

**Comment by JeromeBouvard** [comment]
It's actually a problem with repo and python.
Using the last version of repo from Google fixes the issue.
```
mkdir -p ~/.bin
PATH="${HOME}/.bin:${PATH}"
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
chmod a+rx ~/.bin/repo
```
