### ISSUE TITLE
Question: how can I make multi-vehicle simulation ? 

### ISSUE THREAD

**Issue by cartovarc** [Parrot-Developers/olympe#3]
Hi! I am trying to find in the documentation but I could not find it. can anybody help me :question: Thanks!!

**Comment by cartovarc** [comment]
I will check this: [https://forum.developer.parrot.com/t/running-multiples-drones-in-a-simulation/7646](https://forum.developer.parrot.com/t/running-multiples-drones-in-a-simulation/7646)

**Comment by ndessart** [comment]
Hello,

For question like this you'll find more help on the Parrot developer forum
https://forum.developer.parrot.com/

This question should go directly in the Sphinx category:
https://forum.developer.parrot.com/c/sphinx
Could you please elaborate your question there?

Question regarding Olympe should go in the Olympe category:
https://forum.developer.parrot.com/c/anafi/olympe

Please note that Sphinx is the drone simulator (running full blown simulated firmwares) while Olympe is just the Python programing interface to control a (simulated or physical) drone.

The documentation of Sphinx is available here:
https://developer.parrot.com/docs/sphinx/

**Comment by cartovarc** [comment]
Thank you so much! :)
