### ISSUE TITLE
installation SDK and code script 

### ISSUE THREAD

**Issue by Khaledsamir2021** [Parrot-Developers/olympe#39]
How i can download Olympe SDK on my ANAFI AI drone ?
How i can run python script on Olympe SDK by connected my PC to Drone or by USB ?
Storage of the drone available for software ?

**Comment by ndessart** [comment]
> How i can download Olympe SDK on my ANAFI AI drone ?
Olympe is a ground station controller library. While it should be possible to run Olympe on your Drone it is probably not what you are really looking for.

> How i can run python script on Olympe SDK by connected my PC to Drone or by USB ?

It's explained in the documentation:
https://developer.parrot.com/docs/olympe/index.html

> Storage of the drone available for software ?

Onboard application development is made possible with _Parrot Air SDK Missions_ 
https://developer.parrot.com/docs/index.html
https://developer.parrot.com/docs/airsdk/general/overview.html
